language: csharp

env:
 global:
  - EnableNuGetPackageRestore=false

solution: src/RailNet.sln

cache:
 directories:
  - "src/packages"
  - "tools"

install:
- ls

before_script:
- chmod +x build.sh

script:
 - ./build.sh nunittest
