init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd createpackage
test: off
artifacts:
  - path: deploy\*.nupkg
cache:
  - src\packages -> **\packages.config
  - tools -> build.cmd