// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0-buildscript.1+136.Branch.feature/buildscript.Sha.2560f8035b878980ced1cb7e17ef8e096ac4f80b")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0.0";
    }
}
